# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-10 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='id_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='id_str',
            field=models.CharField(default='0', max_length=30),
            preserve_default=False,
        ),
    ]
