# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0002_auto_20160110_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user_name',
            field=models.CharField(default='themightyzeus', max_length=200),
            preserve_default=False,
        ),
    ]
