# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-11 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0003_tweet_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='user_id_str',
            field=models.CharField(default='000', max_length=200),
            preserve_default=False,
        ),
    ]
