# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0004_tweet_user_id_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_sentiment',
            field=models.IntegerField(default=0),
        ),
    ]
