# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-08 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0006_featurevector'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurevector',
            name='tweet_sentiment',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='featurevector',
            name='user_query',
            field=models.CharField(default='test', max_length=200),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_sentiment',
            field=models.IntegerField(default=-1),
        ),
    ]
