# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_end', '0007_auto_20160208_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('positive', models.IntegerField(default=0)),
                ('negative', models.IntegerField(default=0)),
                ('neutral', models.IntegerField(default=0)),
                ('feature_list', models.CharField(max_length=500)),
            ],
        ),
    ]
